import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "./components/Navbar/Navbar.jsx";
import Footer from "./components/Footer/Footer.jsx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="autumn">
      <body >
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
